dist: trusty
sudo: false

language: node_js
node_js:
  - "6.9"
  - "7.0"
  - "8.0"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable
  # Saucelabs
  sauce_connect: true
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # Saucelabs credentials for global access (including the encrypted access key exported as SAUCE_ACCESS_KEY).
    - SAUCE_USERNAME=rolandjitsu
    - secure: "mVD/EVRIZusNapg6LZpMc1UulNxyrQPUqGH8IBBUNG5fW6V3V/M0BcF3U5BEQbPpUpP8r97cvbw/lv0WNXt2x9wvzEz8UHyBTOebDgORahF8geiSNAZA3Xp21fzEJV3cDDam+
QGkMDzfPMcqMJ95qsBYqN84jw+iS28O2XORrVps69inZCryifH+5cKDuGxSsnpfNjOxO5U4IcAdfpN65643sSDg00AhKJOOSp9eBhcM5bgC75wKoFHD2KKIIKYEuqpBr+OyrnH8asidmYhW9
TUq7Re4xGu5SK9OFMtZDgEZK2ZQ/eLXKWEo7+iBsYAuvphjN8mAQ/pDil2lD8Ljsmagpg08sj8JtBjs0uv+lF48XiaBvOHvz5ppYuxy65YFLYpMzombid9dWMp39cdP4OxIOLcL7SZe0FuB0
KR2m57+nhm8iOhFfoVV/Sx+UIMafT55XTri1jgQiR5dcLNdan5XXOBN3Jz4aVHQE20qUHndD2fzViABgcJgunyXYD8qO81IjXyOg8Wq29e0OdRRcnkDC8mkgqKrXwccMITy2Qabb9eagVQle
DRJtNpZovAo1JExytzLRpf4JRhYPgqU+9TnWyUBQXoIBBzFdBc6uBek5HIb22TuJ7dAxDYuPQLai36nTJ5tKeOnBElctMAgr4rqmORO30d4d3a0ZlB2Xhg="
    # Firebase encrypted token env var (exported as FIREBASE_TOKEN).
    - secure: "CTEy/Dw91rYK75baNy2sqiodY36hIDSSaP+af4FqHp6LxOuVuEnhC3dk+VbsRuR82uA5VTeJjvvOquIrCCfbJSCXG4Hk9w484JD2R4TBfv7qWYVEMrvobzp64hg6DtRO0BsdtJTePfenreaxplEyvUt0LAEKztwgDWfRB5bibAs6BJqTluvwbdWnU/F3OA87EJvHr0N/0R3EcyP3J42zgVsC+54ydh6y6iaCYhuMny+Clh2ifBxRUHzgTWLcts8Xs9B6WhWu1mLILc4daAK9eRZ0uOgzprKLSMfPjoaeh/P7xb3bYc1uT0UyBvfj2MovlDG23teuqSfQc40/yPB/IajZMl7aBdgAc0TvMV6P4V5IG5XW4fHZ+eSGvVSBU2u5Ef8yeBmTfTZDgCooH8xnq5rTLrTlV75XB/uo3D00SbUODX18EUQvbRAlmZakzHwh+YFComS1Uuj2Jz9Eol1X2GUphkWybX6ZsiL+0vwksdKHw1IJBIcId5+li1s7rgR1oCw9AMAPwQuAxE2tHu8sRlrMDsrbOdg7BcyeBGt6/dUqP8Jk5a3uPlzTgKlnCWRuWq2L8y5eU+/pq5Gfvh6vzuqLQt0oBKTZdPAQbmj3mZsS3JnnK+2heJK3IlBrR3JDtC5UsVOyqBkZBm6yZgy5NhjbqFy0JitpUGaf8Jigmkw="
    # Requirement for installing Node 5+
    - CXX=g++-4.8

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Give xvfb some time to start
  - sleep 5

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test:ci
  # E2E tests.
  - npm run e2e:ci

after_success: npm run deploy:ci

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b6bac777adb98ef5dc15
    on_success: change
    on_failure: always
    on_start: never
