dist: trusty
sudo: false

language: node_js
node_js:
  - "7.9"
  - "8.7"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable
  # Saucelabs
  sauce_connect: true
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # Saucelabs credentials for global access (including the encrypted access key exported as SAUCE_ACCESS_KEY).
    - SAUCE_USERNAME=rolandjitsu
    - secure: "JCabDo1wjn+rcfl9R3lXnF0XqPn5xOcm4zUo0+dSAgMiv+/3mC38KGo/fvbsdQzyxTU3hrYUOYk3cp/iI6MQE/h+u/sD0Ixo1B77inGZarSiQqyh93lDPF02NBziwWKOw/KA9PGehlE6SZ4qa55V4A3iOV4+fbwHGzmr/I9QNomAKybAiHrBx/1yA5Q8mFD9AtSgeP9f9vGFqFFFPJIikHdNQL4kF/PoDrn763jHLFVdk1BFd8U/ZV61fArtfxvb1ySMZuIp6GVvOjbDp/hG4hCdcuWiSF0TGQWcvxrzty26mP5qh75yKu9G28l7ln1PLqN/xLEDX7Bv2O5v57eeAGVh49AJjAab3brm69L6KOdJdOnYpCTb6ssrajJMCv+10UV97PYt8yYsUsn+Kg8f8jB0qOHeFwGX0EE9xNKXJOORjRt9gIg/H71XBGXQCMnqHWU2/3NY4XcT6aj4NNv8PkdxXkgV1x2HXs7MqUIk4pfhV+RJd9pbK0WaKc9sAOydyYW+ziEZXk6vCXnTlVoCuCzAFOx74OTuwk0fmNRD8knMW++evyImd5aSc6ENGhvu7MTUehfNSTH+fCSZhT1Ao1E2pSrOAWYl0wHBPPNRsQNEHf7MrzcWB42uM3icPsmoKZHs7+UB+lmY0ejxkI/jj8U2+BBVtf+QthETCDLj1k4="
    # Firebase encrypted token env var (exported as FIREBASE_TOKEN).
    - secure: "gtY2QrWLN/BZ+fJsJww1sP2r8nVFBnuXG+FcRC6yoy8pmvV/0oCE86JlpxsQoRrFKveM2hG0CIohJfv2CZBokPEM0oH5ty74WIqwWsg0Z5KpDM98jX/b3+B6IvaJXD1NC3VJWwR2wMd837EpiB7citkNfhQ8xBrS9x4oLYt3ckzKK40iMgNCOBsvZIZLMgZJgrTEk25STzsLZeTXZsMYRbzjYGN5Ma1ll4N0skpSm0py+c0iXoZgUHOctyAOjdVS+JK3Cj42PpUtI8XImrrJ9i46FPlAjDuvlPzSUZChL+NHohcI89EDY/GrMjvZJFXAY0DSa7SYeWXN8VrQ0M7sp5Oeb6/OA/zMY7XxocJj1Upl3BK/I3myzMsWmLjlLxUAmaz6Kw7ttW/vjfGckzlylOvTmqwn5QFUBlr8vmmTn0JO60l1Y94qOjbfHHE5C19poVDcQZCYJzCkAHGs9Sd6FYZ71esnpujC2SY2yXMZhRoEqlxe/YzfbvupJcsgGeH9HZGfBJqsDou95nHcpcaTASmHKPK92CbiQYZdmuty+pBQzJ/YltPmnFtRz1SviNegSzTioH88UER5FR+4t9Hd5lP5NzVUqURsPUKS1KE9sOyh4zgINpOjd3IsLzr4/4ICZNv1DVmaFW8vbVJO6D31lONlzf+SEenv3d1xXRR3euQ="
    # Requirement for installing Node 5+
    - CXX=g++-4.8

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test:ci
  # E2E tests.
  - npm run e2e:ci

after_success: npm run deploy:ci

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b6bac777adb98ef5dc15
    on_success: change
    on_failure: always
    on_start: never
