dist: trusty
sudo: false

language: node_js
node_js:
  - "8.7"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  chrome: stable
  # Saucelabs
  sauce_connect: true
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # SauceLabs
    - SAUCE_USERNAME=angular-lab
    # SAUCE_ACCESS_KEY
    - secure: "HIMkohNjta17eHaLpVerxnQuwIZNnrymEn8/dEAImoECo+8Z3B9cEHDCdtGgJyK4eLJSk9JWQc7UZQBXkoZw6UyEz8l8f2ZfTGHIVit0Qa3CDDtuVaE2LE0EhV2tUffle9haVqqFE27zgWSCuH5W8G931co81n5UdDgTs9p4gWhsV4/TaQtNzWhfCZuXCzsqeEvrTVFk7O236fiQvcd8TP/+tmi0pAWgUKBe22MKC/aC1OJwYY/4MFyXP0A71SaEeiwssNkJCIjhVnC9w2DnGotCdc/i8s9WMhWQjTaCTsQ7ZgJuM4Ay/q6noEwAcov/QqD3eV6B1WmTOMTNwx+7Hr1UlvITZ5pECc6HYo+3epS0JQ5OWuinNLzHqT7DqZzwh1Q7WZWbU3MX9nTfrRzJZLEBToWBSyiL3Gd/n60pnUPJa5GJNKAusJLb7uADo0sR470qB42X323J8YBVBsohpF1PAqFWYENZjzBrm+9avo4UoUTXlfgXoK5RdMTX8tjHe+KE8D17Uyu87rb4M8BxU485etzam0f0I0/G2fxj8AnPCUwMxkLXKhOYvFQ/PWVV/MTWTzYMDpeAkoPB7+6AWvHGqIcK3qa4yihXVJ4dZDhoarflHklNn+d7LMxZvLx4gOmCdCZ2zORpKPf++2YA6cIb2IFqy/VCDcs/mq3JjgM="
    # Firebase
    # FIREBASE_TOKEN
    - secure: "gtY2QrWLN/BZ+fJsJww1sP2r8nVFBnuXG+FcRC6yoy8pmvV/0oCE86JlpxsQoRrFKveM2hG0CIohJfv2CZBokPEM0oH5ty74WIqwWsg0Z5KpDM98jX/b3+B6IvaJXD1NC3VJWwR2wMd837EpiB7citkNfhQ8xBrS9x4oLYt3ckzKK40iMgNCOBsvZIZLMgZJgrTEk25STzsLZeTXZsMYRbzjYGN5Ma1ll4N0skpSm0py+c0iXoZgUHOctyAOjdVS+JK3Cj42PpUtI8XImrrJ9i46FPlAjDuvlPzSUZChL+NHohcI89EDY/GrMjvZJFXAY0DSa7SYeWXN8VrQ0M7sp5Oeb6/OA/zMY7XxocJj1Upl3BK/I3myzMsWmLjlLxUAmaz6Kw7ttW/vjfGckzlylOvTmqwn5QFUBlr8vmmTn0JO60l1Y94qOjbfHHE5C19poVDcQZCYJzCkAHGs9Sd6FYZ71esnpujC2SY2yXMZhRoEqlxe/YzfbvupJcsgGeH9HZGfBJqsDou95nHcpcaTASmHKPK92CbiQYZdmuty+pBQzJ/YltPmnFtRz1SviNegSzTioH88UER5FR+4t9Hd5lP5NzVUqURsPUKS1KE9sOyh4zgINpOjd3IsLzr4/4ICZNv1DVmaFW8vbVJO6D31lONlzf+SEenv3d1xXRR3euQ="
    # FIREBASE_API_KEY
    - secure: "bztwKslLbnD1DVuN89NzywOvv9foiCJAeYC8p1HatRLPv8HELPkDYz5ZZ2lyM7r3SIB/fOJZfuorh1hBtaaEmtZgVcubVHpTHaGZzdlwRhuNHaJKf0uDQKcLS0tjliShjYTbPQAKaM6bWxLI/o5A+4Rom6d0e9rf6trE2OQIZzZnfszvBSRB/6VTCO34p9OHCqIEnQp2hoZZ940euYWA1gr8TgOwfKQk/isHLOigO0vPPOtLiO8LTb+8kNCWSj5lOvm2atNRniR/U3hGeqG33dkzsN80L3b681x2eQ1jdV/82MqqCEB/cS5IhjIOKJsk5BQme8Q/wgoE3E2Y+sioGYjEEFhYnRrpJaguBqRJZJgKTZ36Jc7L+qsh8Cu76IcfzYQFWtCrVkkLFFnP0hRzHa6EEM/G2+IBTwSm46N3XL4Me3KZJTpR+I1hXLV+h7LUqjN+sak+NObvrz0Ms8dUxWP7XnIKeDgU0PTlZjBlcHKTIEC9wE6CklwG/iGTPPYJLvRApUTWkuJLtRvelcSybDVeXg/cQxG30rUMfX2283u7gVT59FOq/P4FlkjcLi7tEDyLeRUc/mcDhPDtisJ5qSUlLBv7qSx2bKWRSG6EO6xFensSnwop6UvuSgPuu9v3Ju+6Liof3FG0S4ou1JtNELD2mjHAlJI2iYpzXDSKk1E="
    # CMake compiler flags
    # Requirement for installing Node 5+
    - CXX=g++-4.8

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test:ci
  # E2E tests.
  - npm run e2e:ci

after_success: npm run deploy:ci

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b6bac777adb98ef5dc15
    on_success: change
    on_failure: always
    on_start: never
